CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    account_number VARCHAR(18) NOT NULL,
    CONSTRAINT uk_account_account_number UNIQUE (account_number)
);
